### ISSUE TITLE
Missing library 'pango-1.0-0'  when using in azure windows app service

### ISSUE THREAD

**Issue by germinator1512** [berthertogen/weasyprint.wrapped#39]
I've been trying to deploy my dotnet app on a app service in azure. Locally everything works fine, however in azure I get the following error: 

Printing pdf, result has error: $True, error: $Traceback (most recent call last):
  File "C:\home\site\wwwroot\weasyprinter\python\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\home\site\wwwroot\weasyprinter\python\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\home\site\wwwroot\weasyprinter\python\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\weasyprint\__init__.py", line 336, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\weasyprint\css\computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\weasyprint\text\ffi.py", line 421, in <module>
    pango = _dlopen(
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\weasyprint\text\ffi.py", line 407, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\home\site\wwwroot\weasyprinter\python\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

I'm not really sure if this is a problem with the library, hope anybody can help.

**Comment by berthertogen** [comment]
Hello @germinator1512, thanks for checking out the package!!

Can you give a little bit more info on the dotnet app? Is it a simple api that will return the generated PDF?
I will try and setup an example soon, it is this azure service you are using right: https://azure.microsoft.com/en-us/products/app-service/#overview

**Comment by germinator1512** [comment]
Yes, it is a simple API which takes some user input and prints it to a pdf. Dotnet Version 6, Windows App Service. These are the files which are in the app service wwwroot/weasyprinter directory: 
![grafik](https://user-images.githubusercontent.com/65281921/209566811-b5121ce7-cdbd-4035-84ca-01d6882788bd.png)

**Comment by berthertogen** [comment]
Thanks for the extra information, I was able reproduce the issue (in a linux app service) and I am afraid we won't be able to run the wrapper inside the Windows of Linux App Service. Because these services are missing some of the [required components](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation), these components seem to be present on a physical linux/windows server (and offcourse your local os).

However I can provide you with a solution:

You can use containers as a source for an [Azure App Service](https://azure.microsoft.com/en-us/products/app-service/containers/#overview). I have provided a [container image](https://hub.docker.com/repository/docker/berthertogen/aspnet-runtime-6-weayprint-example-api) for asp.net 6 which you can use to host your api.
I've added an Weasyprint.Wrapped.ExampleApi which extends the docker image berthertogen/aspnet-runtime-6-weayprint and hosts the example api.

Use the following steps to deploy your api:

1. Build the docker container using the Dockerfile and deploy the container to dockerhub (or a Azure Container Registry)
2. Create the App Service <<https://learn.microsoft.com/en-us/azure/app-service/tutorial-custom-container?tabs=azure-portal&pivots=container-linux#v-create-the-web-app>>

**Comment by germinator1512** [comment]
I've tried with the official dotnet image "mcr.microsoft.com/dotnet/aspnet:6.0", and the Web App for containers with linux. Getting another error here: 

"OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'"

Could you please provide the Dockerfile From your custom image (berthertogen/aspnet-runtime-6-weayprint-example-api)?
I'm not sure if it was on purpose that you shared the same link twice?

**Comment by berthertogen** [comment]
You can find the Dockerfile in this repository in the .docker folder (https://github.com/berthertogen/weasyprint.wrapped/blob/main/.docker/aspnet-runtime-weayprint/Dockerfile).

**Comment by germinator1512** [comment]
It works, thank you very much for your help!! Is there a way I can donate a coffee for your awesome work? 😄

**Comment by berthertogen** [comment]
Glad to hear it's working @germinator1512 !
Thanks for the offer, but don't have donations setup ;).
